# Bed Master Dataset Generation

## Objective

This notebook creates a **Bed Master Dataset** for the MedTrack project.

The dataset is generated using the **Hospital Master Dataset** and includes bed-related information such as bed ID, ward, room number, bed type, and bed status.

The generated dataset is linked using:
- Admission_ID
- Patient_ID
- Department_ID

The final dataset will be saved as **bed_master.csv** for hospital resource utilization and bed occupancy analysis.

In [1]:
import pandas as pd
import numpy as np
import random
from faker import Faker

fake = Faker()

In [2]:
hospital_master = pd.read_csv(
    "../data/02_processed_data/hospital_master_dataset.csv",
    parse_dates=["Admission_Date", "Discharge_Date"]
)

hospital_master.head()

,Patient_ID,Name,Age,Gender,Diagnosis,Age_Group,Admission_ID,Doctor_ID,Department_ID,Admission_Date,...,Paid,Pending,Surgery_ID,Outcome,Medication_ID,Medicine,Lab_ID,Test,Value,Department_Name
0,P00001,Patient_1,82,Female,Fever,Senior,A00001,DR00186,D002,2025-10-20,...,70001,77,S00001,Success,M00001,Ibuprofen,L00001,Blood Sugar,91.27,Neurology
1,P00002,Patient_2,31,Male,Diabetes,Young Adult,A00002,DR00281,D019,2025-01-21,...,17971,2853,S00002,Complication,M00002,Ibuprofen,L00002,Blood Sugar,175.69,Endocrinology
2,P00003,Patient_3,15,Male,Fever,Child,A00003,DR00105,D020,2025-06-24,...,6228,204,S00003,Complication,M00003,Ibuprofen,L00003,Cholesterol,150.60,Dental
3,P00004,Patient_4,50,Female,Asthma,Adult,A00004,DR00312,D004,2025-07-23,...,77817,4853,S00004,Complication,M00004,Insulin,L00004,Cholesterol,176.53,Pediatrics
4,P00005,Patient_5,17,Female,Diabetes,Child,A00005,DR00430,D018,2025-04-06,...,7571,2805,S00005,Complication,M00005,Ibuprofen,L00005,Blood Sugar,133.46,Ophthalmology

In [3]:
hospital_master = pd.read_csv(
    "../data/02_processed_data/hospital_master_dataset.csv",
    parse_dates=["Admission_Date", "Discharge_Date"]
)

hospital_master.head()

,Patient_ID,Name,Age,Gender,Diagnosis,Age_Group,Admission_ID,Doctor_ID,Department_ID,Admission_Date,...,Paid,Pending,Surgery_ID,Outcome,Medication_ID,Medicine,Lab_ID,Test,Value,Department_Name
0,P00001,Patient_1,82,Female,Fever,Senior,A00001,DR00186,D002,2025-10-20,...,70001,77,S00001,Success,M00001,Ibuprofen,L00001,Blood Sugar,91.27,Neurology
1,P00002,Patient_2,31,Male,Diabetes,Young Adult,A00002,DR00281,D019,2025-01-21,...,17971,2853,S00002,Complication,M00002,Ibuprofen,L00002,Blood Sugar,175.69,Endocrinology
2,P00003,Patient_3,15,Male,Fever,Child,A00003,DR00105,D020,2025-06-24,...,6228,204,S00003,Complication,M00003,Ibuprofen,L00003,Cholesterol,150.60,Dental
3,P00004,Patient_4,50,Female,Asthma,Adult,A00004,DR00312,D004,2025-07-23,...,77817,4853,S00004,Complication,M00004,Insulin,L00004,Cholesterol,176.53,Pediatrics
4,P00005,Patient_5,17,Female,Diabetes,Child,A00005,DR00430,D018,2025-04-06,...,7571,2805,S00005,Complication,M00005,Ibuprofen,L00005,Blood Sugar,133.46,Ophthalmology

In [4]:
ward_mapping = {
    "Cardiology": "Cardiac Ward",
    "Neurology": "Neuro Ward",
    "Orthopedics": "Orthopedic Ward",
    "Pediatrics": "Pediatric Ward",
    "Oncology": "Cancer Ward",
    "Emergency": "Emergency Ward",
    "General Medicine": "General Ward",
    "Dermatology": "Skin Care Ward",
    "Gynecology": "Maternity Ward",
    "Psychiatry": "Mental Health Ward"
}

In [5]:
bed_types = [
    "General",
    "Semi-Private",
    "Private",
    "ICU"
]

In [6]:
bed_status = [
    "Occupied",
    "Available",
    "Reserved",
    "Cleaning",
    "Maintenance"
]

In [7]:
bed_master = pd.DataFrame()

bed_master["Bed_ID"] = [
    f"B{i:05d}" for i in range(1, len(hospital_master)+1)
]

bed_master["Admission_ID"] = hospital_master["Admission_ID"]

bed_master["Patient_ID"] = hospital_master["Patient_ID"]

bed_master["Department_ID"] = hospital_master["Department_ID"]

bed_master["Department_Name"] = hospital_master["Department_Name"]

bed_master["Ward"] = hospital_master["Department_Name"].apply(
    lambda x: ward_mapping.get(x, "General Ward")
)

bed_master["Floor"] = [
    random.randint(1,6)
    for _ in range(len(hospital_master))
]

bed_master["Room_Number"] = [
    random.randint(100,699)
    for _ in range(len(hospital_master))
]

bed_master["Bed_Number"] = [
    random.randint(1,4)
    for _ in range(len(hospital_master))
]

bed_master["Bed_Type"] = [
    random.choice(bed_types)
    for _ in range(len(hospital_master))
]

bed_master["Bed_Status"] = [
    random.choice(bed_status)
    for _ in range(len(hospital_master))
]

bed_master["Admission_Date"] = hospital_master["Admission_Date"]

bed_master["Discharge_Date"] = hospital_master["Discharge_Date"]

bed_master["Length_of_Stay"] = hospital_master["Length_of_Stay"]

In [8]:
bed_master.info()

bed_master.head()

bed_master.sample(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Bed_ID           5000 non-null   object
 1   Admission_ID     5000 non-null   object
 2   Patient_ID       5000 non-null   object
 3   Department_ID    5000 non-null   object
 4   Department_Name  5000 non-null   object
 5   Ward             5000 non-null   object
 6   Floor            5000 non-null   int64
 7   Room_Number      5000 non-null   int64
 8   Bed_Number       5000 non-null   int64
 9   Bed_Type         5000 non-null   object
 10  Bed_Status       5000 non-null   object
 11  Admission_Date   5000 non-null   datetime64[ns]
 12  Discharge_Date   5000 non-null   datetime64[ns]
 13  Length_of_Stay   5000 non-null   int64
dtypes: datetime64[ns](2), int64(4), object(8)
memory usage: 547.0+ KB

,Bed_ID,Admission_ID,Patient_ID,Department_ID,Department_Name,Ward,Floor,Room_Number,Bed_Number,Bed_Type,Bed_Status,Admission_Date,Discharge_Date,Length_of_Stay
4863,B04864,A04864,P04864,D011,Gynecology,Maternity Ward,3,147,4,Semi-Private,Maintenance,2025-02-03,2025-02-12,9
975,B00976,A00976,P00976,D006,ENT,General Ward,3,572,1,Semi-Private,Available,2025-01-17,2025-01-19,2
3290,B03291,A03291,P03291,D012,Psychiatry,Mental Health Ward,2,363,4,Semi-Private,Maintenance,2025-07-16,2025-07-24,8
4418,B04419,A04419,P04419,D015,Emergency,Emergency Ward,2,105,3,General,Maintenance,2025-07-24,2025-07-26,2
3574,B03575,A03575,P03575,D010,Nephrology,General Ward,3,181,3,Private,Occupied,2025-07-22,2025-07-30,8

In [9]:
print("Rows :", bed_master.shape[0])

print("Columns :", bed_master.shape[1])

print("\nMissing Values")

print(bed_master.isnull().sum())

print("\nDuplicate Rows")

print(bed_master.duplicated().sum())

Rows : 5000
Columns : 14

Missing Values
Bed_ID             0
Admission_ID       0
Patient_ID         0
Department_ID      0
Department_Name    0
Ward               0
Floor              0
Room_Number        0
Bed_Number         0
Bed_Type           0
Bed_Status         0
Admission_Date     0
Discharge_Date     0
Length_of_Stay     0
dtype: int64

Duplicate Rows
0

In [10]:
bed_master.to_csv(
    "../data/02_processed_data/bed_master.csv",
    index=False
)

print("bed_master.csv saved successfully.")

bed_master.csv saved successfully.